package com.sz.mapper;

import com.sz.pojo.AppCategory;

import java.util.List;

public interface AppCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbg.generated
     */
    int insert(AppCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbg.generated
     */
    int insertSelective(AppCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbg.generated
     */
    AppCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppCategory record);

    List<AppCategory> queryAllLevelOne();

    List<AppCategory> queryParent(Long id);
}