package com.sz.mapper;

import com.sz.pojo.DevUser;

import java.util.List;

public interface DevUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbg.generated
     */
    int insert(DevUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbg.generated
     */
    int insertSelective(DevUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbg.generated
     */
    DevUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DevUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DevUser record);


    List<DevUser> queryByNamePwd(DevUser devUser);




}