package com.sz.pojo;

import com.sz.obj.AppUntilObj;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class AppInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.software_name
     *
     * @mbg.generated
     */
    private String softwareName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.apk_name
     *
     * @mbg.generated
     */
    private String apkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.support_trom
     *
     * @mbg.generated
     */
    private String supportTrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.interface_language
     *
     * @mbg.generated
     */
    private String interfaceLanguage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.software_size
     *
     * @mbg.generated
     */
    private BigDecimal softwareSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.update_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.dev_id
     *
     * @mbg.generated
     */
    private Long devId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.app_info
     *
     * @mbg.generated
     */
    private String appInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.status
     *
     * @mbg.generated
     */
    private Long status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.onsale_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date onsaleDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.offsale_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date offsaleDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.flatfrom_id
     *
     * @mbg.generated
     */
    private Long flatfromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.category_level3
     *
     * @mbg.generated
     */
    private Long categoryLevel3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.down_loads
     *
     * @mbg.generated
     */
    private Long downLoads;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.created_by
     *
     * @mbg.generated
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.creation_date
     *
     * @mbg.generated
     */

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.modify_by
     *
     * @mbg.generated
     */
    private Long modifyBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.modify_datee
     *
     * @mbg.generated
     */
    private Date modifyDatee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.category_level1
     *
     * @mbg.generated
     */
    private Long categoryLevel1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.category_level2
     *
     * @mbg.generated
     */
    private Long categoryLevel2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.logopic_path
     *
     * @mbg.generated
     */
    private String logopicPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.logoloc_path
     *
     * @mbg.generated
     */
    private String logolocPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.version_id
     *
     * @mbg.generated
     */
    private Long versionId;

    private List<AppVersion> appVersions;

    private AppVersion newAppVersion;

    private AppCategory appCategorylevel1;
    private AppCategory appCategorylevel2;
    private AppCategory appCategorylevel3;
    private DevUser devUser;
    private  DevUser createUser;
    private  DevUser modifyUser;
    private AppUntilObj appUntilObj;


    public DevUser getCreateUser() {
        return createUser;
    }

    public void setCreateUser(DevUser createUser) {
        this.createUser = createUser;
    }

    public DevUser getModifyUser() {
        return modifyUser;
    }

    public void setModifyUser(DevUser modifyUser) {
        this.modifyUser = modifyUser;
    }

    public DevUser getDevUser() {
        return devUser;
    }

    public void setDevUser(DevUser devUser) {
        this.devUser = devUser;
    }

    public AppUntilObj getAppUntilObj() {
        return appUntilObj;
    }

    public void setAppUntilObj(AppUntilObj appUntilObj) {
        this.appUntilObj = appUntilObj;
    }

    public AppCategory getAppCategorylevel1() {
        return appCategorylevel1;
    }

    public void setAppCategorylevel1(AppCategory appCategorylevel1) {
        this.appCategorylevel1 = appCategorylevel1;
    }

    public AppCategory getAppCategorylevel2() {
        return appCategorylevel2;
    }

    public void setAppCategorylevel2(AppCategory appCategorylevel2) {
        this.appCategorylevel2 = appCategorylevel2;
    }

    public AppCategory getAppCategorylevel3() {
        return appCategorylevel3;
    }

    public void setAppCategorylevel3(AppCategory appCategorylevel3) {
        this.appCategorylevel3 = appCategorylevel3;
    }

    public List<AppVersion> getAppVersions() {
        return appVersions;
    }

    public void setAppVersions(List<AppVersion> appVersions) {
        this.appVersions = appVersions;
    }

    public AppVersion getNewAppVersion() {
        return newAppVersion;
    }

    public void setNewAppVersion(AppVersion newAppVersion) {
        this.newAppVersion = newAppVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.id
     *
     * @return the value of app_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.id
     *
     * @param id the value for app_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.software_name
     *
     * @return the value of app_info.software_name
     *
     * @mbg.generated
     */
    public String getSoftwareName() {
        return softwareName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.software_name
     *
     * @param softwareName the value for app_info.software_name
     *
     * @mbg.generated
     */
    public void setSoftwareName(String softwareName) {
        this.softwareName = softwareName == null ? null : softwareName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.apk_name
     *
     * @return the value of app_info.apk_name
     *
     * @mbg.generated
     */
    public String getApkName() {
        return apkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.apk_name
     *
     * @param apkName the value for app_info.apk_name
     *
     * @mbg.generated
     */
    public void setApkName(String apkName) {
        this.apkName = apkName == null ? null : apkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.support_trom
     *
     * @return the value of app_info.support_trom
     *
     * @mbg.generated
     */
    public String getSupportTrom() {
        return supportTrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.support_trom
     *
     * @param supportTrom the value for app_info.support_trom
     *
     * @mbg.generated
     */
    public void setSupportTrom(String supportTrom) {
        this.supportTrom = supportTrom == null ? null : supportTrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.interface_language
     *
     * @return the value of app_info.interface_language
     *
     * @mbg.generated
     */
    public String getInterfaceLanguage() {
        return interfaceLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.interface_language
     *
     * @param interfaceLanguage the value for app_info.interface_language
     *
     * @mbg.generated
     */
    public void setInterfaceLanguage(String interfaceLanguage) {
        this.interfaceLanguage = interfaceLanguage == null ? null : interfaceLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.software_size
     *
     * @return the value of app_info.software_size
     *
     * @mbg.generated
     */
    public BigDecimal getSoftwareSize() {
        return softwareSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.software_size
     *
     * @param softwareSize the value for app_info.software_size
     *
     * @mbg.generated
     */
    public void setSoftwareSize(BigDecimal softwareSize) {
        this.softwareSize = softwareSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.update_date
     *
     * @return the value of app_info.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.update_date
     *
     * @param updateDate the value for app_info.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.dev_id
     *
     * @return the value of app_info.dev_id
     *
     * @mbg.generated
     */
    public Long getDevId() {
        return devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.dev_id
     *
     * @param devId the value for app_info.dev_id
     *
     * @mbg.generated
     */
    public void setDevId(Long devId) {
        this.devId = devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.app_info
     *
     * @return the value of app_info.app_info
     *
     * @mbg.generated
     */
    public String getAppInfo() {
        return appInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.app_info
     *
     * @param appInfo the value for app_info.app_info
     *
     * @mbg.generated
     */
    public void setAppInfo(String appInfo) {
        this.appInfo = appInfo == null ? null : appInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.status
     *
     * @return the value of app_info.status
     *
     * @mbg.generated
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.status
     *
     * @param status the value for app_info.status
     *
     * @mbg.generated
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.onsale_date
     *
     * @return the value of app_info.onsale_date
     *
     * @mbg.generated
     */
    public Date getOnsaleDate() {
        return onsaleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.onsale_date
     *
     * @param onsaleDate the value for app_info.onsale_date
     *
     * @mbg.generated
     */
    public void setOnsaleDate(Date onsaleDate) {
        this.onsaleDate = onsaleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.offsale_date
     *
     * @return the value of app_info.offsale_date
     *
     * @mbg.generated
     */
    public Date getOffsaleDate() {
        return offsaleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.offsale_date
     *
     * @param offsaleDate the value for app_info.offsale_date
     *
     * @mbg.generated
     */
    public void setOffsaleDate(Date offsaleDate) {
        this.offsaleDate = offsaleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.flatfrom_id
     *
     * @return the value of app_info.flatfrom_id
     *
     * @mbg.generated
     */
    public Long getFlatfromId() {
        return flatfromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.flatfrom_id
     *
     * @param flatfromId the value for app_info.flatfrom_id
     *
     * @mbg.generated
     */
    public void setFlatfromId(Long flatfromId) {
        this.flatfromId = flatfromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.category_level3
     *
     * @return the value of app_info.category_level3
     *
     * @mbg.generated
     */
    public Long getCategoryLevel3() {
        return categoryLevel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.category_level3
     *
     * @param categoryLevel3 the value for app_info.category_level3
     *
     * @mbg.generated
     */
    public void setCategoryLevel3(Long categoryLevel3) {
        this.categoryLevel3 = categoryLevel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.down_loads
     *
     * @return the value of app_info.down_loads
     *
     * @mbg.generated
     */
    public Long getDownLoads() {
        return downLoads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.down_loads
     *
     * @param downLoads the value for app_info.down_loads
     *
     * @mbg.generated
     */
    public void setDownLoads(Long downLoads) {
        this.downLoads = downLoads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.created_by
     *
     * @return the value of app_info.created_by
     *
     * @mbg.generated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.created_by
     *
     * @param createdBy the value for app_info.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.creation_date
     *
     * @return the value of app_info.creation_date
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.creation_date
     *
     * @param creationDate the value for app_info.creation_date
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.modify_by
     *
     * @return the value of app_info.modify_by
     *
     * @mbg.generated
     */
    public Long getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.modify_by
     *
     * @param modifyBy the value for app_info.modify_by
     *
     * @mbg.generated
     */
    public void setModifyBy(Long modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.modify_datee
     *
     * @return the value of app_info.modify_datee
     *
     * @mbg.generated
     */
    public Date getModifyDatee() {
        return modifyDatee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.modify_datee
     *
     * @param modifyDatee the value for app_info.modify_datee
     *
     * @mbg.generated
     */
    public void setModifyDatee(Date modifyDatee) {
        this.modifyDatee = modifyDatee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.category_level1
     *
     * @return the value of app_info.category_level1
     *
     * @mbg.generated
     */
    public Long getCategoryLevel1() {
        return categoryLevel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.category_level1
     *
     * @param categoryLevel1 the value for app_info.category_level1
     *
     * @mbg.generated
     */
    public void setCategoryLevel1(Long categoryLevel1) {
        this.categoryLevel1 = categoryLevel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.category_level2
     *
     * @return the value of app_info.category_level2
     *
     * @mbg.generated
     */
    public Long getCategoryLevel2() {
        return categoryLevel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.category_level2
     *
     * @param categoryLevel2 the value for app_info.category_level2
     *
     * @mbg.generated
     */
    public void setCategoryLevel2(Long categoryLevel2) {
        this.categoryLevel2 = categoryLevel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.logopic_path
     *
     * @return the value of app_info.logopic_path
     *
     * @mbg.generated
     */
    public String getLogopicPath() {
        return logopicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.logopic_path
     *
     * @param logopicPath the value for app_info.logopic_path
     *
     * @mbg.generated
     */
    public void setLogopicPath(String logopicPath) {
        this.logopicPath = logopicPath == null ? null : logopicPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.logoloc_path
     *
     * @return the value of app_info.logoloc_path
     *
     * @mbg.generated
     */
    public String getLogolocPath() {
        return logolocPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.logoloc_path
     *
     * @param logolocPath the value for app_info.logoloc_path
     *
     * @mbg.generated
     */
    public void setLogolocPath(String logolocPath) {
        this.logolocPath = logolocPath == null ? null : logolocPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.version_id
     *
     * @return the value of app_info.version_id
     *
     * @mbg.generated
     */
    public Long getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.version_id
     *
     * @param versionId the value for app_info.version_id
     *
     * @mbg.generated
     */
    public void setVersionId(Long versionId) {
        this.versionId = versionId;
    }
}