package com.sz.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class AppVersion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.app_id
     *
     * @mbg.generated
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.version_no
     *
     * @mbg.generated
     */
    private String versionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.version_info
     *
     * @mbg.generated
     */
    private String versionInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.publish_status
     *
     * @mbg.generated
     */
    private Long publishStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.downLoad_link
     *
     * @mbg.generated
     */
    private String downloadLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.version_size
     *
     * @mbg.generated
     */
    private BigDecimal versionSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.created_by
     *
     * @mbg.generated
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.creation_date
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.modify_by
     *
     * @mbg.generated
     */
    private Long modifyBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.modify_date
     *
     * @mbg.generated
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.apkLoc_path
     *
     * @mbg.generated
     */
    private String apklocPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.apk_filename
     *
     * @mbg.generated
     */
    private String apkFilename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.id
     *
     * @return the value of app_version.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.id
     *
     * @param id the value for app_version.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.app_id
     *
     * @return the value of app_version.app_id
     *
     * @mbg.generated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.app_id
     *
     * @param appId the value for app_version.app_id
     *
     * @mbg.generated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.version_no
     *
     * @return the value of app_version.version_no
     *
     * @mbg.generated
     */
    public String getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.version_no
     *
     * @param versionNo the value for app_version.version_no
     *
     * @mbg.generated
     */
    public void setVersionNo(String versionNo) {
        this.versionNo = versionNo == null ? null : versionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.version_info
     *
     * @return the value of app_version.version_info
     *
     * @mbg.generated
     */
    public String getVersionInfo() {
        return versionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.version_info
     *
     * @param versionInfo the value for app_version.version_info
     *
     * @mbg.generated
     */
    public void setVersionInfo(String versionInfo) {
        this.versionInfo = versionInfo == null ? null : versionInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.publish_status
     *
     * @return the value of app_version.publish_status
     *
     * @mbg.generated
     */
    public Long getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.publish_status
     *
     * @param publishStatus the value for app_version.publish_status
     *
     * @mbg.generated
     */
    public void setPublishStatus(Long publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.downLoad_link
     *
     * @return the value of app_version.downLoad_link
     *
     * @mbg.generated
     */
    public String getDownloadLink() {
        return downloadLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.downLoad_link
     *
     * @param downloadLink the value for app_version.downLoad_link
     *
     * @mbg.generated
     */
    public void setDownloadLink(String downloadLink) {
        this.downloadLink = downloadLink == null ? null : downloadLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.version_size
     *
     * @return the value of app_version.version_size
     *
     * @mbg.generated
     */
    public BigDecimal getVersionSize() {
        return versionSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.version_size
     *
     * @param versionSize the value for app_version.version_size
     *
     * @mbg.generated
     */
    public void setVersionSize(BigDecimal versionSize) {
        this.versionSize = versionSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.created_by
     *
     * @return the value of app_version.created_by
     *
     * @mbg.generated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.created_by
     *
     * @param createdBy the value for app_version.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.creation_date
     *
     * @return the value of app_version.creation_date
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.creation_date
     *
     * @param creationDate the value for app_version.creation_date
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.modify_by
     *
     * @return the value of app_version.modify_by
     *
     * @mbg.generated
     */
    public Long getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.modify_by
     *
     * @param modifyBy the value for app_version.modify_by
     *
     * @mbg.generated
     */
    public void setModifyBy(Long modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.modify_date
     *
     * @return the value of app_version.modify_date
     *
     * @mbg.generated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.modify_date
     *
     * @param modifyDate the value for app_version.modify_date
     *
     * @mbg.generated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.apkLoc_path
     *
     * @return the value of app_version.apkLoc_path
     *
     * @mbg.generated
     */
    public String getApklocPath() {
        return apklocPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.apkLoc_path
     *
     * @param apklocPath the value for app_version.apkLoc_path
     *
     * @mbg.generated
     */
    public void setApklocPath(String apklocPath) {
        this.apklocPath = apklocPath == null ? null : apklocPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.apk_filename
     *
     * @return the value of app_version.apk_filename
     *
     * @mbg.generated
     */
    public String getApkFilename() {
        return apkFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.apk_filename
     *
     * @param apkFilename the value for app_version.apk_filename
     *
     * @mbg.generated
     */
    public void setApkFilename(String apkFilename) {
        this.apkFilename = apkFilename == null ? null : apkFilename.trim();
    }
}