package com.sz.pojo;

import java.util.Date;

public class DataDictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.type_code
     *
     * @mbg.generated
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.type_name
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.value_id
     *
     * @mbg.generated
     */
    private Integer valueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.value_name
     *
     * @mbg.generated
     */
    private String valueName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.create_by
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.creation_date
     *
     * @mbg.generated
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.modify_by
     *
     * @mbg.generated
     */
    private String modifyBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.modify_date
     *
     * @mbg.generated
     */
    private String modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.id
     *
     * @return the value of data_dictionary.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.id
     *
     * @param id the value for data_dictionary.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.type_code
     *
     * @return the value of data_dictionary.type_code
     *
     * @mbg.generated
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.type_code
     *
     * @param typeCode the value for data_dictionary.type_code
     *
     * @mbg.generated
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.type_name
     *
     * @return the value of data_dictionary.type_name
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.type_name
     *
     * @param typeName the value for data_dictionary.type_name
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.value_id
     *
     * @return the value of data_dictionary.value_id
     *
     * @mbg.generated
     */
    public Integer getValueId() {
        return valueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.value_id
     *
     * @param valueId the value for data_dictionary.value_id
     *
     * @mbg.generated
     */
    public void setValueId(Integer valueId) {
        this.valueId = valueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.value_name
     *
     * @return the value of data_dictionary.value_name
     *
     * @mbg.generated
     */
    public String getValueName() {
        return valueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.value_name
     *
     * @param valueName the value for data_dictionary.value_name
     *
     * @mbg.generated
     */
    public void setValueName(String valueName) {
        this.valueName = valueName == null ? null : valueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.create_by
     *
     * @return the value of data_dictionary.create_by
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.create_by
     *
     * @param createBy the value for data_dictionary.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.creation_date
     *
     * @return the value of data_dictionary.creation_date
     *
     * @mbg.generated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.creation_date
     *
     * @param creationDate the value for data_dictionary.creation_date
     *
     * @mbg.generated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.modify_by
     *
     * @return the value of data_dictionary.modify_by
     *
     * @mbg.generated
     */
    public String getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.modify_by
     *
     * @param modifyBy the value for data_dictionary.modify_by
     *
     * @mbg.generated
     */
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy == null ? null : modifyBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.modify_date
     *
     * @return the value of data_dictionary.modify_date
     *
     * @mbg.generated
     */
    public String getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.modify_date
     *
     * @param modifyDate the value for data_dictionary.modify_date
     *
     * @mbg.generated
     */
    public void setModifyDate(String modifyDate) {
        this.modifyDate = modifyDate == null ? null : modifyDate.trim();
    }
}