package com.sz.pojo;

import java.util.Date;

public class DevUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.devCode
     *
     * @mbg.generated
     */
    private String devCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.devName
     *
     * @mbg.generated
     */
    private String devName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.devPassword
     *
     * @mbg.generated
     */
    private String devPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.devEmail
     *
     * @mbg.generated
     */
    private String devEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.createBy
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.creatioinDate
     *
     * @mbg.generated
     */
    private Date creatioinDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.modifyBy
     *
     * @mbg.generated
     */
    private Long modifyBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.modifyDate
     *
     * @mbg.generated
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.id
     *
     * @return the value of dev_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.id
     *
     * @param id the value for dev_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.devCode
     *
     * @return the value of dev_user.devCode
     *
     * @mbg.generated
     */
    public String getDevCode() {
        return devCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.devCode
     *
     * @param devCode the value for dev_user.devCode
     *
     * @mbg.generated
     */
    public void setDevCode(String devCode) {
        this.devCode = devCode == null ? null : devCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.devName
     *
     * @return the value of dev_user.devName
     *
     * @mbg.generated
     */
    public String getDevName() {
        return devName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.devName
     *
     * @param devName the value for dev_user.devName
     *
     * @mbg.generated
     */
    public void setDevName(String devName) {
        this.devName = devName == null ? null : devName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.devPassword
     *
     * @return the value of dev_user.devPassword
     *
     * @mbg.generated
     */
    public String getDevPassword() {
        return devPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.devPassword
     *
     * @param devPassword the value for dev_user.devPassword
     *
     * @mbg.generated
     */
    public void setDevPassword(String devPassword) {
        this.devPassword = devPassword == null ? null : devPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.devEmail
     *
     * @return the value of dev_user.devEmail
     *
     * @mbg.generated
     */
    public String getDevEmail() {
        return devEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.devEmail
     *
     * @param devEmail the value for dev_user.devEmail
     *
     * @mbg.generated
     */
    public void setDevEmail(String devEmail) {
        this.devEmail = devEmail == null ? null : devEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.createBy
     *
     * @return the value of dev_user.createBy
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.createBy
     *
     * @param createBy the value for dev_user.createBy
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.creatioinDate
     *
     * @return the value of dev_user.creatioinDate
     *
     * @mbg.generated
     */
    public Date getCreatioinDate() {
        return creatioinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.creatioinDate
     *
     * @param creatioinDate the value for dev_user.creatioinDate
     *
     * @mbg.generated
     */
    public void setCreatioinDate(Date creatioinDate) {
        this.creatioinDate = creatioinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.modifyBy
     *
     * @return the value of dev_user.modifyBy
     *
     * @mbg.generated
     */
    public Long getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.modifyBy
     *
     * @param modifyBy the value for dev_user.modifyBy
     *
     * @mbg.generated
     */
    public void setModifyBy(Long modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.modifyDate
     *
     * @return the value of dev_user.modifyDate
     *
     * @mbg.generated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.modifyDate
     *
     * @param modifyDate the value for dev_user.modifyDate
     *
     * @mbg.generated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}